name: taskly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  firebase_auth: ^4.19.0
  firebase_database: ^10.5.0 
  provider: ^6.0.5
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/logo.svg
    - images/google_logo.png
    - images/taskly-home.svg
    - images/profile.png
    - images/plus.svg